### ISSUE TITLE
extends nested object class

### ISSUE THREAD

**Issue by koba04** [h13i32maru/esdoc#5]
Currently, an error occurs when target files includes extending nested object class.

```js
import React from 'react';
/**
 * This is App
 */
export default class App extends React.Component {
  /**
  * @return {ReactElement} markup
  */
  render() {
    React.createElement('div', {});
  }
}
```

* error trace

```
TypeError: Cannot read property 'match' of null
    at CoverageBuilder._findByName (/Users/koba04/project/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:124:25)
    at extendsChain (/Users/koba04/project/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:365:47)
    at DocResolver._resolveExtendsChain (/Users/koba04/project/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:550:11)
    at DocResolver.resolve (/Users/koba04/project/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:56:12)
    at CoverageBuilder.DocBuilder (/Users/koba04/project/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:53:42)
    at new CoverageBuilder (/Users/koba04/project/node_modules/esdoc/out/src/Publisher/Builder/CoverageBuilder.js:32:19)
    at publish (/Users/koba04/project/node_modules/esdoc/out/src/Publisher/publish.js:116:35)
    at Function.generate (/Users/koba04/project/node_modules/esdoc/out/src/ESDoc.js:185:7)
    at ESDocCLI.exec (/Users/koba04/project/node_modules/esdoc/out/src/ESDocCLI.js:90:28)
    at Object.<anonymous> (/Users/koba04/project/node_modules/esdoc/out/src/ESDocCLI.js:192:7)
```

Do you have a plan that support this case?

**Comment by h13i32maru** [comment]
@koba04 I fixed this issue and will release this fixing in next version :sunny:

**Comment by koba04** [comment]
awesome!!! :clap: 
This is a great news for React users! :star2: 

Thank you :smile:
